project:
  type: book

book:
  title: "How to Make a Thesis Template"
  author: "Doran Penner"
  date: "May 2026"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd  # TODO always needed, what should it contain?
    - dedication.qmd
    # and now we get to the main sections!
    - intro.qmd
    - summary.qmd
    # - chapters/chap3.qmd  # TODO organize later
  appendices:
    - glossary.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  # html is for quickly viewing, the final
  # thesis will always be a pdf
  html: default
  pdf:
    documentclass: scrbook
    template-partials:
      - before-body.tex
    lof: false  # set to `true` if you want a list of figures
